import type { Metadata } from "next";
import "./globals.css";

import { DarkModeProvider } from "./_context/DarkModeContext";
import ToastProvider from "./_utils/ToastProvider";
import ReactQueryProvider from "./_utils/ReactQueryProvider";
import { Poppins, Sono } from "next/font/google";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--fontFamily_Poppins",
});

const sono = Sono({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
  variable: "--fontFamily_Sono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-[62.5%]">
      <body
        className={`${poppins.className} ${sono.variable} text-[1.4rem] text-gray-700 dark:text-gray-200`}
      >
        <ReactQueryProvider>
          <DarkModeProvider>
            <ToastProvider>{children}</ToastProvider>
          </DarkModeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
